[build]
command="npm run build"
publish="dist/"

[dev]
framework="#custom"
command="npm start"
targetPort=1234
autoLaunch=false

[[redirects]]
from="/graph"
to="/.netlify/functions/proxyNetligraph"
status=200